#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXmu
Version  : 1.1.2
Release  : 6
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXmu-1.1.2.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXmu-1.1.2.tar.gz
Summary  : Mini Xmu Library
Group    : Development/Tools
License  : MIT-Opengroup
Requires: libXmu-lib
Requires: libXmu-doc
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xt)
BuildRequires : xmlto

%description
This library contains miscellaneous utilities and is not part of the Xlib
standard.  It contains routines which only use public interfaces so that it
may be layered on top of any proprietary implementation of Xlib or Xt.

%package dev
Summary: dev components for the libXmu package.
Group: Development
Requires: libXmu-lib

%description dev
dev components for the libXmu package.


%package doc
Summary: doc components for the libXmu package.
Group: Documentation

%description doc
doc components for the libXmu package.


%package lib
Summary: lib components for the libXmu package.
Group: Libraries

%description lib
lib components for the libXmu package.


%prep
%setup -q -n libXmu-1.1.2

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xmu/Atoms.h
/usr/include/X11/Xmu/CharSet.h
/usr/include/X11/Xmu/CloseHook.h
/usr/include/X11/Xmu/Converters.h
/usr/include/X11/Xmu/CurUtil.h
/usr/include/X11/Xmu/CvtCache.h
/usr/include/X11/Xmu/DisplayQue.h
/usr/include/X11/Xmu/Drawing.h
/usr/include/X11/Xmu/Editres.h
/usr/include/X11/Xmu/EditresP.h
/usr/include/X11/Xmu/Error.h
/usr/include/X11/Xmu/ExtAgent.h
/usr/include/X11/Xmu/Initer.h
/usr/include/X11/Xmu/Lookup.h
/usr/include/X11/Xmu/Misc.h
/usr/include/X11/Xmu/StdCmap.h
/usr/include/X11/Xmu/StdSel.h
/usr/include/X11/Xmu/SysUtil.h
/usr/include/X11/Xmu/WhitePoint.h
/usr/include/X11/Xmu/WidgetNode.h
/usr/include/X11/Xmu/WinUtil.h
/usr/include/X11/Xmu/Xct.h
/usr/include/X11/Xmu/Xmu.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libXmu/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
