#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v5
# autospec commit: c02b2fe
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libXmu
Version  : 1.2.0
Release  : 19
URL      : https://www.x.org/releases/individual/lib/libXmu-1.2.0.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libXmu-1.2.0.tar.gz
Source1  : https://www.x.org/releases/individual/lib/libXmu-1.2.0.tar.gz.sig
Summary  : Xmu Library
Group    : Development/Tools
License  : MIT
Requires: libXmu-lib = %{version}-%{release}
Requires: libXmu-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glib-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libxslt-bin
BuildRequires : pkg-config
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xextproto)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xt)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xt)
BuildRequires : xmlto
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libXmu - X miscellaneous utility routines library
-------------------------------------------------

%package dev
Summary: dev components for the libXmu package.
Group: Development
Requires: libXmu-lib = %{version}-%{release}
Provides: libXmu-devel = %{version}-%{release}
Requires: libXmu = %{version}-%{release}

%description dev
dev components for the libXmu package.


%package dev32
Summary: dev32 components for the libXmu package.
Group: Default
Requires: libXmu-lib32 = %{version}-%{release}
Requires: libXmu-dev = %{version}-%{release}

%description dev32
dev32 components for the libXmu package.


%package doc
Summary: doc components for the libXmu package.
Group: Documentation

%description doc
doc components for the libXmu package.


%package lib
Summary: lib components for the libXmu package.
Group: Libraries
Requires: libXmu-license = %{version}-%{release}

%description lib
lib components for the libXmu package.


%package lib32
Summary: lib32 components for the libXmu package.
Group: Default
Requires: libXmu-license = %{version}-%{release}

%description lib32
lib32 components for the libXmu package.


%package license
Summary: license components for the libXmu package.
Group: Default

%description license
license components for the libXmu package.


%prep
%setup -q -n libXmu-1.2.0
cd %{_builddir}/libXmu-1.2.0
pushd ..
cp -a libXmu-1.2.0 build32
popd
pushd ..
cp -a libXmu-1.2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711373995
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1711373995
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libXmu
cp %{_builddir}/libXmu-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libXmu/a0e09a5a7029b42c7cb5d43f71b3d2d981234810 || :
export GOAMD64=v2
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xmu/Atoms.h
/usr/include/X11/Xmu/CharSet.h
/usr/include/X11/Xmu/CloseHook.h
/usr/include/X11/Xmu/Converters.h
/usr/include/X11/Xmu/CurUtil.h
/usr/include/X11/Xmu/CvtCache.h
/usr/include/X11/Xmu/DisplayQue.h
/usr/include/X11/Xmu/Drawing.h
/usr/include/X11/Xmu/Editres.h
/usr/include/X11/Xmu/EditresP.h
/usr/include/X11/Xmu/Error.h
/usr/include/X11/Xmu/ExtAgent.h
/usr/include/X11/Xmu/Initer.h
/usr/include/X11/Xmu/Lookup.h
/usr/include/X11/Xmu/Misc.h
/usr/include/X11/Xmu/StdCmap.h
/usr/include/X11/Xmu/StdSel.h
/usr/include/X11/Xmu/SysUtil.h
/usr/include/X11/Xmu/WhitePoint.h
/usr/include/X11/Xmu/WidgetNode.h
/usr/include/X11/Xmu/WinUtil.h
/usr/include/X11/Xmu/Xct.h
/usr/include/X11/Xmu/Xmu.h
/usr/lib64/libXmu.so
/usr/lib64/libXmuu.so
/usr/lib64/pkgconfig/xmu.pc
/usr/lib64/pkgconfig/xmuu.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXmu.so
/usr/lib32/libXmuu.so
/usr/lib32/pkgconfig/32xmu.pc
/usr/lib32/pkgconfig/32xmuu.pc
/usr/lib32/pkgconfig/xmu.pc
/usr/lib32/pkgconfig/xmuu.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libXmu/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libXmu.so.6.2.0
/V3/usr/lib64/libXmuu.so.1.0.0
/usr/lib64/libXmu.so.6
/usr/lib64/libXmu.so.6.2.0
/usr/lib64/libXmuu.so.1
/usr/lib64/libXmuu.so.1.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXmu.so.6
/usr/lib32/libXmu.so.6.2.0
/usr/lib32/libXmuu.so.1
/usr/lib32/libXmuu.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libXmu/a0e09a5a7029b42c7cb5d43f71b3d2d981234810
